### ISSUE TITLE
Hi I am Interested on your project

### ISSUE THREAD

**Issue by ggplab** [ubergarm/RimWorld-RimLog#2]
Hi   I am one of Rimworld user and interesting about your project. 

Actually, I'd like to also summary gamelog so I find out rws file exists.

I find out history, battlelog, talemanger tag for summarizing.  but when i look  history there is only recent event not from start. 

Could you let me know where is start event log and any useful tag?

I saw you code but i just good at python so i can't recognize what you refer on. 

Thank you

**Comment by ubergarm** [comment]
Thanks for your interest @bellepoque7 !

The `RWS` file is the rimworld save game file, right?

If I recall, the save game does not save every history/battlelog/tale/etc forever. A given event has an importance weight and slowly it decays until it is replaced by new events. This probably prevents the save game file from growing forever - only more recent and most important events will remain over time.

So, unfortunately, unless you start to log a new save game, you probably can't get out the earliest events which are lost.

I hope that helps some! Thanks and good luck!
